version: '3.8'

services:
  # Development service
  app-dev:
    build: 
      context: .
      target: builder
    ports:
      - "3001:3001"
    env_file: .env
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - postgres

  # Production service
  app-prod:
    build: .
    ports:
      - "3001:3001"
    env_file: .env
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres

  # Database service
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=habeebdindi
      - POSTGRES_DB=arcastai
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 